In [1]:
# 通用函数：快速的元素级数组函数
import numpy as np

In [2]:
arr = np.arange(10)
np.sqrt(arr) # ufunc ,作用在每个元素上

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x,y) # 二元函数，接收2个数组作为参数，并按对应位置进行操作

array([ 0.31113719, -0.48284775,  0.27248627, -0.80411424,  0.09873837,
        1.32821214,  0.77762233,  0.64458861])

In [5]:
arr = np.random.randn(7)*5
print(arr)
np.modf(arr) # 分别打印小数与整数部分

[ 4.39347928 -4.62628476  8.46085453 -4.94627966 -3.34844047 -3.27746078
 -1.01488042]


(array([ 0.39347928, -0.62628476,  0.46085453, -0.94627966, -0.34844047,
        -0.27746078, -0.01488042]), array([ 4., -4.,  8., -4., -3., -3., -1.]))

## 一元 ufunc

In [13]:
# 一元ufunc
# abs/fabs   计算绝对值
print(np.abs(arr))
print(np.fabs(arr))

[4.39347928 4.62628476 8.46085453 4.94627966 3.34844047 3.27746078
 1.01488042]
[4.39347928 4.62628476 8.46085453 4.94627966 3.34844047 3.27746078
 1.01488042]


In [14]:
# sqrt 开平方
# square 平方
# exp  e的指数
arr = np.arange(5)
print('exp', np.exp(arr))
#log/log10/log2/log1p log1p=log(1+x)   对数函数

exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [17]:
# sign  符号函数，返回数值的符号，大于0返回1，等于0返回0，小于0返回-1
arr = np.random.randn(5)
np.sign(arr)

array([-1., -1.,  1., -1.,  1.])

In [18]:
# ceil 向上取整
# floor 向下取整
# rint  四舍五入
# modf 将数组的小数和整数部分以两个独立的数组的形式返回
arr = np.random.randn(5)
print('arr', arr)
print('ceil \t', np.ceil(arr))
print('floor \t', np.floor(arr))
print('rint \t', np.rint(arr))

arr [ 0.36151637 -2.37118686 -1.31156239  0.01559523 -0.05098488]
ceil 	 [ 1. -2. -1.  1. -0.]
floor 	 [ 0. -3. -2.  0. -1.]
rint 	 [ 0. -2. -1.  0. -0.]


In [21]:
# isnan 数组元素是否为空，返回一个boolean型数组
# isfinite/isinf  是否是isinf, isneginf, isposinf, isnan/是否是无穷
# cos/cosh
# sin/sinh
# tan/tanh
# arrcos/arccosh
# arrsin/arcsinh
# arrtan/arctanh
# logical_not   计算各元素not x的真值，相当于~arr。

## 二元ufunc

In [23]:
# add   加
# subtract   减
arr1 = np.arange(5)
arr2 = np.random.randn(5)
print('arr1 \t',arr1)
print('arr2 \t',arr2)
print('subtract \t', np.subtract(arr1,arr2))#arr1-arr2

arr1 	 [0 1 2 3 4]
arr2 	 [ 0.08566676 -0.91097632  0.67708984  0.8356161  -0.460764  ]
subtract 	 [-0.08566676  1.91097632  1.32291016  2.1643839   4.460764  ]


In [24]:
# multiply 乘
# divide/floor_divide   除/向下整除
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([11,21,31,41,51])
print('divide \t', np.divide(arr2,arr1))
print('floor_divide \t', np.floor_divide(arr2,arr1))

divide 	 [11.         10.5        10.33333333 10.25       10.2       ]
floor_divide 	 [11 10 10 10 10]


In [26]:
# power  几次幂
np.power(arr1,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [29]:
# maximun/fmax
# minimum/fmin
# mod   取余
arr1 = np.array([2,3,4])
arr2 = np.array([7,8,9])
print('mod \t',np.mod(arr2,arr1))

mod 	 [1 2 1]


In [31]:
# copysign   复制正负号，arr1的符号按照arr2的来变
arr1 = np.random.randn(5)
print('arr1 \t', arr1)
arr2 = np.random.randn(5)
print('arr2 \t', arr2)
np.copysign(arr1,arr2)

arr1 	 [ 0.05485602  3.71488879 -0.07717368 -0.89080238  0.16984522]
arr2 	 [-0.6909973  -1.32930467  2.56231874 -0.37639707  0.12790843]


array([-0.05485602, -3.71488879,  0.07717368, -0.89080238,  0.16984522])

In [36]:
# greater/greater_equal   大于/大于等于
# less/less_equal   小于/小于等于
# equal/not_equal   等于/不等于
# logic_and/or/xor   逻辑与/或/异或
arr1 = np.array([4,0,0])
arr2 = np.array([4,3,0])
print('logic_and \t',np.logical_and(arr1,arr2))
print('logic_or \t',np.logical_or(arr1,arr2))
print('logic_xor \t',np.logical_xor(arr1,arr2))

logic_and 	 [ True False False]
logic_or 	 [ True  True False]
logic_xor 	 [False  True False]
